name: Overleaf Sync with Git
on:
  schedule:
    - cron: "0 * * * *"
  push:
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - run: |
        git remote add overleaf https://git:${OVERLEAF_COOKIE}@git.overleaf.com/${OVERLEAF_PROJECT_ID}
        git pull --rebase overleaf master && git push --force origin main
        #git push overleaf master
      env:
        OVERLEAF_PROJECT_ID: ${{ secrets.OVERLEAF_PROJECT_ID }}
        OVERLEAF_COOKIE: ${{ secrets.OVERLEAF_COOKIE }}
